# https://jekyllrb.com/docs/configuration/

#
# Jekyll Settings
#
baseurl: ""
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Brad Christie"
      layout: "post"
      image: "/assets/img/placeholder-1280x853.png"
      thumbnail: "/assets/img/placeholder-320x213.png"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
excerpt_separator: "<!-- more -->"
future: true
permalink: :year/:month/:day/:title/
timezone: America/New_York
webrick:
  headers:
    X-Powered-By: Caffiene

#
# Site Settings
#
title: Brad Christie
description: "A website and blog for Brad Christie."
slogan: "Learn.\r\nCreate.\r\nImpress."

technologies: "C# .NET,Entity Framework,Git,HTML,JavaScript,jQuery,KnockoutJS,MySQL,NodeJS,PHP,Sitecore,SQL Server,TypeScript"
#facebook_username: bradedward
linkedin_username: bradachristie
twitter_username: bradachristie
github_username:  bradchristie-me




# Site layout settings
mutli_lang: true